### ISSUE TITLE
Load a Schema using PHP

### ISSUE THREAD

**Issue by psrpinto** [WordPress/try-wordpress#136]
In #134 we have defined the structure of a _Schema_. We now need a way to load a schema into PHP code.

Probably something along these lines:

```php
function get_schemas(): array
```

We also need to figure out how to make the schema files accessible to the PHP code (e.g. by having webpack copy them somewhere).

**Comment by ashfame** [comment]
I think it would make more sense if the schema is defined in PHP and then exposed to frontend via an API call.

**Comment by psrpinto** [comment]
I think loading them from the API makes a lot of sense! So we'd adapt #135 to get them from an API endpoint. This would mean we should implement that endpoint when we address this ticket.

**Comment by akirk** [comment]
I can see a lot of sense in it too, I am just worried that it means that we'd now need to wait for WordPress Playground to boot before we can get the post types and thus be able to use the extension.

In my original proposal I had all functionality inside WordPress and we scrapped it in favor of splitting out a JS-Only extension so that it can load much faster than WordPress Playground. 

How would you combine these two concerns?

**Comment by akirk** [comment]
We decided to not create an API from which JS would get its schemas but instead load the schemas from JSON files from the filesystem.

**Comment by akirk** [comment]
This will use the build process created in #144
