### ISSUE TITLE
Backend API Design

### ISSUE THREAD

**Issue by ashfame** [WordPress/try-wordpress#152]
This issue aims to finalize the API design so that API operates completely off defined schema.

Right now, API completely abstracts the WordPress-y details & offers a simple flatten object for interaction. For this, we define custom controller classes (one for each subject type) which extends WP_REST_Controller and registers the REST API routes. This is the recommended way of rolling out custom endpoints so we still leverage what core offers in terms of handling the REST API such as arguments validation and sanitization.

**Example for creating a resource:**
```
POST /try-wp/v1/blog-posts
{
   "sourceUrl":"https:\/\/example.org\/Blogpost_Controller_Test\/testCreateItemFullBody",
   "sourceHtml":"<html><head><title><\/title><\/head><body><div><p>This is the test content.<\/p><\/div><\/body><\/html>",
   "rawTitle":"<h1>This is the test title<\/h1>",
   "parsedTitle":"This is the test title",
   "rawContent":"<div><p>This is the test content.<\/p><\/div>",
   "parsedContent":"<p>This is the test content.<\/p>",
   "rawDate":"<time>25 Oct 2024 18:39:20<\/time>",
   "parsedDate":"2024-10-25T18:39:20.000Z",
   "authorId":23
}
```
Response:
```
{
   "id":4,
   "authorId":23,
   "sourceUrl":"https:\/\/example.org\/Blogpost_Controller_Test\/testCreateItemFullBody",
   "sourceHtml":"<html><head><title><\/title><\/head><body><div><p>This is the test content.<\/p><\/div><\/body><\/html>",
   "rawTitle":"<h1>This is the test title<\/h1>",
   "parsedTitle":"This is the test title",
   "rawDate":"<time>25 Oct 2024 18:39:20<\/time>",
   "parsedDate":"2024-10-25 18:39:20",
   "rawContent":"<div><p>This is the test content.<\/p><\/div>",
   "parsedContent":"<p>This is the test content.<\/p>",
   "transformedId":"5",
   "previewUrl":"http:\/\/localhost:8889\/this-is-the-test-title"
}
```

This allows us to have complete control over the API endpoints with the exact request and response body as needed.

-------
Now, we have a couple of questions to explore:

1) Do we use a singular endpoint for all subject types? OR different ones are better?
2) What endpoints to use? Custom ones as detailed above or the default ones we get automatically from registering custom post types?

**Comment by ashfame** [comment]
Lets compare the pros and cons:

## 1) Singular vs Multiple endpoints

Singular endpoints PROS

- Simpler client integration

Singular endpoints CONS

- Request & Response body becomes more generic vs strict contract

Multiple endpoints PROS

- Strict contract with Request & Response body

Multiple endpoints CONS

- Client must know (if not able to deduce) what endpoint to use for any subject type

**Comment by ashfame** [comment]
## 2) Custom endpoints vs WP Default endpoints

Custom endpoints PROS

- Full control over API behavior
- Simple Request & Response body
- We can choose to store certain fields to posts table and rest in postmeta table, without complicating the API or implementation
- Easier to implement & maintain

Custom endpoints CONS

- More work than default endpoints, but already done at this point

Default endpoints PROS

- Little work required for endpoints setup

Default endpoints CONS

- By default, each post type get its own endpoint. So, if we want different endpoints for each subject type, we must store them separately in multiple custom post types
- A singular endpoint to receive all subject types is only possible, if we store data in a single custom post type and store everything in postmeta table
- A bit less easier to implement & maintain since require bunch of hooks and filters to control/tweak the behavior
- REST API is not dead simple and requires a bit of WordPress knowledge to use the REST API i.e. discard irrelevant fields or filter them out and only look under meta fields

**Comment by ashfame** [comment]
@psrpinto @akirk Please provide your inputs on other considerations we have for finalizing the Backend's API design.

**Comment by akirk** [comment]
Isn't it feasible to implement both a REST endpoint and use the WordPress REST endpoints and compare it? I am not sure I'd assess the pros and cons like you but the amount of work to get it implemented should be not so large to not just try both of them.

> By default, each post type get its own endpoint. So, if we want different endpoints for each subject type, we must store them separately in multiple custom post types

Could you explain why this is a con to you?

> A bit less easier to implement & maintain since require bunch of hooks and filters to control/tweak the behavior

Dito, I am not sure why this is more difficult?

> REST API is not dead simple and requires a bit of WordPress knowledge to use the REST API i.e. discard irrelevant fields or filter them out and only look under meta fields

In times of AI support in development, I'd argue that standard WordPress REST endpoints are likely to be implemented correct.

**Comment by psrpinto** [comment]
There's a lot to consider in what concerns the API design (as visible by what @ashame wrote above) so I think we should think about it indeed separately from other concerns (e.g. how data is stored and accessed). Thank you @ashfame for opening this ticket, which will allow us to discuss the API design on its own.

Below are my thoughts about this topic.

---

I think it makes sense indeed to think about the API design independently of how the data will then be stored and accessed. I think we should aim to decouple those two things (API design vs How data is stored and accessed) because that will give us the most flexible system in case we need to change things in the future.

## Default endpoints vs custom endpoints

One of the purposes of an HTTP API, in my view, is that it allows changing the internals of the system while keeping the clients working without any changes. It should be possible for us to completely re-arrange how we store the data while keeping the same exact API (within certain limits, of course).

AFAICT, when using WP default endpoints, details of how the data is stored are "leaked" to the API. For example, a request to update a meta field looks something like this:

```json
{
    "meta": {
        "foo": "bar"
    }
}
```

This means that the fact that the system is internally storing `foo` as a meta field of a post is now exposed to the API. If tomorrow we decide that we no longer want to store `foo` as a meta field of a post, the clients would need to change.

To me, this is a point against using default WP endpoints, because it would defeat one of the purposes of our API: to decouple how data is stored from the API design.

In the example above, you could make the case that it would still be possible to change the internals of how the data is stored without changing the clients, by hooking into WordPress and overriding the default behavior, which would indeed be a possibility AFAICT.

However, that would defeat the sole advantage of using the WP default endpoints, which is that we can leverage the code that WordPress already provides to save things in the default places.

Another aspect to consider regarding the default WP endpoints is that, AFAICT, they apply validation that would not necessarily be appropriate for our use case. For example, I think that there are some fields that are mandatory (post body?) which might not necessarily fit with what we want. In that case, we would again need to hook into WP to override the default behavior.

At this point, instead of using the WP default endpoints and overriding them to function the way we want them to, we might as well just use custom endpoints, which makes things much more flexible for us, and allow us to fully separate the API design from details of how the data is stored and accessed.

## Singular vs Multiple endpoints

I will provide my thoughts about this in a later comment.

**Comment by ashfame** [comment]
@akirk Please see my responses below:

> Isn't it feasible to implement both a REST endpoint and use the WordPress REST endpoints and compare it? I am not sure I'd assess the pros and cons like you but the amount of work to get it implemented should be not so large to not just try both of them.

While it's technically feasible, my recommendation comes from analyzing the architectural implications rather than implementation effort. However, I'm curious what specific comparison metrics you'd find valuable?

> > By default, each post type get its own endpoint. So, if we want different endpoints for each subject type, we must store them separately in multiple custom post types

> Could you explain why this is a con to you?

It's about the architectural constraint it imposes. When data is forced into WordPress's post type model, it limits our ability to model the domain in ways that might better serve our specific use case. We'd be adapting our domain model to fit WordPress's structure rather than the other way around.

> > A bit less easier to implement & maintain since require bunch of hooks and filters to control/tweak the behavior

> Dito, I am not sure why this is more difficult?

Regarding hooks and filters: The challenge isn't their complexity in isolation, but rather about code organization and maintainability. Direct implementation allows us to encapsulate related functionality in a single, cohesive unit. With hooks and filters, the business logic becomes distributed across multiple callback functions, making it harder to reason about the system's behavior as a whole.

> > REST API is not dead simple and requires a bit of WordPress knowledge to use the REST API i.e. discard irrelevant fields or filter them out and only look under meta fields

> In times of AI support in development, I'd argue that standard WordPress REST endpoints are likely to be implemented correct.

I was considering this from the API consumer's perspective. Client would need to understand WordPress's specific data structure to effectively use the API, rather than working with a domain-specific API that matches their exact needs.

**Comment by ashfame** [comment]
@psrpinto Thank you for the detailed analysis! I completely agree with your take. API endpoints spawned via registration of custom post types are a contract for interacting with that custom post type, so should be used only when the goal is to save data in that specific post type. For anything else, it works only if that's the storage layer but at the cost of tighter coupling. And as you said, if we ever want to change anything in storage layer, that breaks the API.

> Another aspect to consider regarding the default WP endpoints is that, AFAICT, they apply validation that would not necessarily be appropriate for our use case. For example, I think that there are some fields that are mandatory (post body?) which might not necessarily fit with what we want. In that case, we would again need to hook into WP to override the default behavior.

You probably are referring to the validation error when we try to save an empty post, right? That happens inside of `wp_insert_post()` and we use a `wp_insert_post_empty_content` filter to work around it.

But regarding the arguments validation, as we all previously discussed, that's possible in both endpoint approaches. We are already making use of that today in our custom controller classes.

**Comment by akirk** [comment]
I understand the feeling of not being in control when using an automatically provided endpoint. I also can see where potentially we run into a place where something in the design works against us. But also, I haven't yet seen it. I am not (yet) convinced that we need it.

Instead, I see [all the work that goes into a new endpoint](https://github.com/WordPress/try-wordpress/pull/153/files#diff-9ade2ec8a11fff628377a5c9d033e5f97c6c1fa3b9ae456d99ade3b124bd9e50), maintaining the dynamic fields, etc. I think the best code is the one that you didn't need to write and someone else maintains (given that they do maintain it, but I have a positive feeling there for WordPress).

Right now [the exploration](https://github.com/WordPress/try-wordpress/pull/153/files#diff-9ade2ec8a11fff628377a5c9d033e5f97c6c1fa3b9ae456d99ade3b124bd9e50) is 600 lines of code and we still have hardcoded title, content and date. It's just much less code needed [if we go for the builtin solution](https://gist.github.com/akirk/226c85e05a32969ca5099326248329bf).

I understand the argument about having to know the intrinsics of the REST API. But this is nothing that needs to be implemented by anyone else. Just the frontend needs to know how to exactly call the endpoint.

@psrpinto said:
> This means that the fact that the system is internally storing foo as a meta field of a post is now exposed to the API. If tomorrow we decide that we no longer want to store foo as a meta field of a post, the clients would need to change.
> To me, this is a point against using default WP endpoints, because it would defeat one of the purposes of our API: to decouple how data is stored from the API design.

I would agree if this were the API. But it isn't. I see JS and PHP as a whole, something that we fully control. Moving the data from JS to PHP is a necessary evil that we accepted to go into when we split it. If we decide to change the data representation, we can do this on both ends.

So maybe a fundamental misalignment here is that you see the REST endpoints as a public API, while I see them as a part of the system? Why do you see it as a public API?

**Comment by psrpinto** [comment]
> So maybe a fundamental misalignment here is that you see the REST endpoints as a public API, while I see them as a part of the system? Why do you see it as a public API?

Sorry, I didn't mean to imply that I see the API being consumed by other things other than our frontend. I see the API as indeed something that is only used by our frontend. However, even then, I would still maintain that it would be beneficial for it to be possible to change how we store/access data in the backend without needing to make changes to the frontend.

--- 

> See the Summary at the end for a TLDR

There's a lot of good points made above by you both @akirk and @ashfame. If I would summarize the topics under discussion I would describe it as follows. My goal here is to try to find some common ground, because I think we're all making valid points, and I believe it's possible to reach a solution that covers everyone's points.
## Requirements

From what I can take from the points we're all making above, our requirements here are:

1. We need an API (to be consumed only by our frontend), which allows storing and querying subjects. A subject represents a "thing" that is imported from a source site (blog post, page, etc). From now on I will refer to this API as the Subjects API.
2. The Subjects API allows the frontend to do the following (the ones that the frontend currently requires are marked with `*`, we would only need to implement the other ones when/if needed):
    - `*` Create a new subject
    - `*` Update a subject 
    - `*` Find a subject by its `slug` AND `sourceUrl`
    - Find a subject by its `id`
    - Find all subjects with a given `slug`
3. We want to it to be possible to add a new subject (e.g. product) and not need to make **any** changes to the code that powers the Subjects API or the frontend.
4. We want to leverage REST API functionality already provided by WP as much as possible. Specifically, we want to use the request validation that WP provides out of the box for custom post types.
5. We want to be able to change how we store a subject in the database without needing to make **any** changes to the API nor the frontend.

Did I miss something here @akirk @asfame? If so, please comment below and I will make sure to include them in this list, and adapt the proposed solution below accordingly.

I would like to add an extra requirement here that has more to do with facilitating our work than the API design itself:

6. We want to be able to design and implement the API without considering **any** details of how the data is stored/accessed. This is so that we can discuss/implement the API without also needing to solve, simultaneously, how the data is stored/accessed. If we don't make this split, the PR that fixes this ticket (the one we're discussing) will contain the implementation of the full system. Instead, we want that PR to only implement the API, and basically leave the "controllers" empty.
## Proposed solution that addresses the above requirements

### Custom endpoints

A request to update a subject using the default WP endpoints would look something like:

```json
"meta": {
	"field_date": "<serialized date field>",
	"field_title": "<serialized title field>",
	"field_content": "<serialized content field>"
}
```

This means that we'd be exposing to the API that the data is stored as meta fields, so we would not be able to fulfill requirement 5. For this reason, I would rule out using default WP endpoints in favor of implementing our own custom endpoints that we can design as we see fit. 

As an example, here's how the request to update a subject would look like when using custom endpoints:

```json
{
    "fields": {
	    "date": {
		    "raw": "<date>...</date>",
		    "parsed": "2024-12-31 12:00:00"
	    },
	    "title": {
		    "raw": "<h1>hello</h1>",
		    "parsed": "hello"
	    },
	    "content": {
		    "raw": "<div>hello</div>",
		    "parsed": "<block markup>"
	    },
    }
}
```

### Validation

Using custom endpoints does not necessarily prevent us from using default functionality provided by WordPress in what concerns, for example, validating requests. I would assume that we would be able to programmatically call the default validation, if we would consider that the default validation would be useful to us.

Additionally, if we want, we could add additional validation of our own on top of the default validation provided by WordPress. For example, validating that a `field` has the correct structure.

Programmatically calling WP's default validation would address requirement 4.

My suggestion would be to to create a new ticket that is only about validation so that we can look at that topic later, independently from other topics being discussed here.
### One endpoint vs multiple endpoints

Given that the choice between using one endpoint vs multiple endpoints does not relate to any of the requirements above, I would leave that choice to whoever implements the PR that tackles this issue.

The choice comes down to whether we'd have a single set of endpoints for all subjects types:

```
/wp-json/try-wordpress/subjects/foo
/wp-json/try-wordpress/subjects/bar
```

or one set of endpoints per subject type:

```
/wp-json/try-wordpress/blog-posts/foo
/wp-json/try-wordpress/blog-posts/bar

/wp-json/try-wordpress/pages/foo
/wp-json/try-wordpress/pages/bar
```

Note that if we choose the latter, the endpoints would automatically be registered from `schema.json`, we would **NOT** be coding them separately. More on this in the next section.

If I may, personally, I don't see an advantage with opting for the multiple endpoints, so if it would be me implementing the PR, I would choose a single set of endpoints.
### `schema.json`

`schema.json` is what allows us to address requirement 3. If in the previous section we opted for single set of endpoints, there's nothing to do here. If instead we opted for one set of endpoints per subject type, then they need to be automatically registered.

In that case, we would:

- Load `schema.json` into memory (#136)
- For each subject type
	- Register the endpoints for that subject type

### Data storage/access

In the PR that addresses this ticket, the "controllers" would be left empty. This addresses requirement 6.

### Summary

I believe this proposed solution address all requirements listed above. Here's what we'd need to do to implement the proposed solution:

- Create a ticket specifically for validation of requests
- #136
- If we opt for multiple endpoints
    - For each subject type in `schema.json`
        - Register the endpoints for that subject type, as custom endpoints
- If we opt for single set of endpoints
    - Register the endpoints (in this case, `schema.json` is not used to register endpoints)
- Leave the "controllers" empty
- So that the app keeps functioning, I would suggest that we register these new endpoints while keeping the existing "legacy" endpoints in place. We can delete them later.
- That's it

@akirk @ashfame  If you have additional requirements, please list them below, and please do also mention any issues you find with the proposed solution. We can then iterate on the proposed solution until all requirements are addressed.

One final request from my side: when you provide feedback in this issue, please consider requirement 6. If you don't agree with that requirement, let's discuss it on Slack instead of in this issue, as it has more to do with the way we work than the design of the API.

**Comment by akirk** [comment]
We agreed on moving forward with a custom endpoint, not only but also, to ensure what @psrpinto mentioned as "requirement 6" to make it easier to hide any upcoming storage changes.

@ashfame has already started to modify the existing endpoint to use the schema in #165.
